# vim: set ts=2 et:
# deployer bundle for stable charms
# UOSCI relies on this for OS-on-OS deployment testing
base-services:
  services:
    rabbitmq-server:
      charm: cs:rabbitmq-server
      constraints: mem=1G
    ceph-mon:
      charm: cs:ceph-mon
      num_units: 3
      constraints: mem=1G
      options:
        expected-osd-count: 3
    ceph-osd:
      charm: cs:ceph-osd
      num_units: 3
      constraints: mem=1G
      storage:
        osd-devices: cinder,10G
    keystone:
      charm: cs:keystone
      constraints: mem=1G
      options:
        admin-password: openstack
        admin-token: ubuntutesting
    openstack-dashboard:
      charm: cs:openstack-dashboard
      constraints: mem=1G
    nova-compute:
      charm: cs:nova-compute
      num_units: 3
      constraints: mem=4G
      options:
        enable-live-migration: True
        enable-resize: True
        migration-auth-type: ssh
    nova-cloud-controller:
      charm: cs:nova-cloud-controller
      constraints: mem=2G
      options:
        network-manager: Neutron
    neutron-gateway:
      charm: cs:neutron-gateway
      constraints: mem=4G
      options:
        instance-mtu: 1300
        bridge-mappings: physnet1:br-ex
    neutron-api:
      charm: cs:neutron-api
      constraints: mem=1G
      options:
        neutron-security-groups: True
        enable-ml2-port-security: True
        enable-qos: True
        enable-vlan-trunking: True
        flat-network-providers: physnet1
    neutron-openvswitch:
      charm: cs:neutron-openvswitch
    cinder:
      charm: cs:cinder
      options:
        block-device: "None"
        glance-api-version: 2
      constraints: mem=1G
    cinder-ceph:
      charm: cs:cinder-ceph
    glance:
      charm: cs:glance
      constraints: mem=1G
    swift-proxy:
      charm: cs:swift-proxy
      constraints: mem=1G
      options:
        zone-assignment: manual
        replicas: 3
        swift-hash: fdfef9d4-8b06-11e2-8ac0-531c923c8fae
    swift-storage-z1:
      charm: cs:swift-storage
      constraints: mem=1G
      options:
        zone: 1
      storage:
        block-devices: cinder,10G
    swift-storage-z2:
      charm: cs:swift-storage
      constraints: mem=1G
      options:
        zone: 2
      storage:
        block-devices: cinder,10G
    swift-storage-z3:
      charm: cs:swift-storage
      constraints: mem=1G
      options:
        zone: 3
      storage:
        block-devices: cinder,10G
    ceilometer:
      charm: cs:ceilometer
      constraints: mem=1G
    ceilometer-agent:
      charm: cs:ceilometer-agent
    heat:
      charm: cs:heat
  relations:
    - [ keystone, mysql ]
    - - nova-cloud-controller:shared-db
      - mysql:shared-db
    - - nova-cloud-controller:amqp
      - rabbitmq-server:amqp
    - [ nova-cloud-controller, glance ]
    - [ nova-cloud-controller, keystone ]
    - [ nova-compute, nova-cloud-controller ]
    - - nova-compute
      - rabbitmq-server:amqp
    - [ nova-compute, glance ]
    - [ nova-compute, ceph-mon ]
    - [ glance, mysql ]
    - [ glance, keystone ]
    - [ glance, ceph-mon ]
    - [ glance, "cinder:image-service" ]
    - [ glance, rabbitmq-server ]
    - [ cinder, mysql ]
    - [ cinder, rabbitmq-server ]
    - [ cinder, nova-cloud-controller ]
    - [ cinder, keystone ]
    - [ cinder, cinder-ceph ]
    - [ cinder-ceph, ceph-mon ]
    - [ neutron-gateway, nova-cloud-controller ]
    - - openstack-dashboard:identity-service
      - keystone:identity-service
    - [ swift-proxy, keystone ]
    - [ swift-proxy, swift-storage-z1 ]
    - [ swift-proxy, swift-storage-z2 ]
    - [ swift-proxy, swift-storage-z3 ]
    - - ceilometer
      - keystone:identity-service
    - - ceilometer:amqp
      - rabbitmq-server:amqp
    - [ ceilometer-agent, nova-compute ]
    - [ ceilometer-agent, ceilometer ]
    - [ ceilometer-agent, rabbitmq-server ]
    - [ heat, mysql ]
    - [ heat, keystone ]
    - [ heat, rabbitmq-server ]
    - [ "neutron-gateway:amqp", rabbitmq-server ]
    - [ neutron-api, mysql ]
    - [ neutron-api, rabbitmq-server ]
    - [ neutron-api, nova-cloud-controller ]
    - [ neutron-api, neutron-openvswitch ]
    - [ neutron-api, keystone ]
    - [ neutron-api, neutron-gateway ]
    - [ neutron-openvswitch, nova-compute ]
    - [ neutron-openvswitch, rabbitmq-server ]
    - [ ceph-osd, ceph-mon ]
openstack-services:
  inherits: base-services
openstack-services-trusty-mitaka:
  inherits: openstack-services
  services:
    aodh:
      charm: cs:aodh
      constraints: mem=1G
    memcached:
      charm: cs:memcached
      constraints: mem=1G
    designate:
      charm: cs:designate
      constraints: mem=1G
      options:
        nameservers: 'ns1.ubuntu.com'
        nova-domain: 'serverstack.ubuntu.com.'
        neutron-domain: 'serverstack.ubuntu.com.'
        nova-domain-email: 'bob@serverstack.ubuntu.com'
        neutron-domain-email: 'bob@serverstack.ubuntu.com'
    designate-bind:
      charm: cs:designate-bind
  relations:
    - [ aodh, rabbitmq-server ]
    - [ aodh, mysql ]
    - [ aodh, keystone ]
    - [ designate, keystone ]
    - [ designate, mysql ]
    - [ designate, rabbitmq-server ]
    - [ designate, designate-bind ]
    - [ designate, memcached ]
openstack-services-xenial:
  inherits: openstack-services-trusty-mitaka
openstack-services-xenial-ocata:
  inherits: openstack-services-xenial
  services:
    gnocchi:
      charm: cs:~openstack-charmers-next/gnocchi
    memcached:
      charm: cs:memcached
  relations:
    - [ gnocchi, ceph-mon ]
    - [ gnocchi, mysql ]
    - [ gnocchi, rabbitmq-server ]
    - [ gnocchi, memcached ]
    - [ gnocchi, ceilometer ]
    - [ gnocchi, keystone ]
    - [ cinder-ceph, nova-compute ]
openstack-services-queens:
  inherits: openstack-services-xenial-ocata
  relations:
    - - ceilometer
      - keystone:identity-credentials
    - - designate:dnsaas
      - neutron-api:external-dns
openstack-services-rocky:
  inherits: openstack-services-queens
  services:
    barbican:
      charm: cs:~openstack-charmers-next/barbican
      constraints: mem=1G
  relations:
    - [ barbican, rabbitmq-server ]
    - [ barbican, mysql ]
    - [ barbican, keystone ]
openstack-services-train:
  inherits: openstack-services-rocky
  services:
    placement:
      charm: cs:placement
      constraints: mem=1G
  relations:
    - [ placement, mysql ]
    - [ placement, keystone ]
    - [ placement, nova-cloud-controller ]
# icehouse
trusty-icehouse:
  inherits: openstack-services
  series: trusty
  services:
    mongodb:
      branch: https://git.launchpad.net/mongodb-charm
      constraints: mem=1G
    mysql:
      charm: cs:percona-cluster
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
        root-password: ChangeMe123
        sst-password: ChangeMe123
  relations:
    - [ ceilometer, mongodb ]
trusty-icehouse-proposed:
  inherits: trusty-icehouse
  overrides:
    source: proposed
    openstack-origin: distro-proposed
trusty-icehouse-trunk:
  inherits: trusty-icehouse
  overrides:
    openstack-origin: ppa:openstack-ubuntu-testing/icehouse
    source: ppa:openstack-ubuntu-testing/icehouse
    offline-compression: "no"
# mitaka
trusty-mitaka:
  #NOTE(coreycb): Temporarily disable reactive charms until
  #               https://bugs.launchpad.net/bugs/1643027 is resolved.
  #inherits: openstack-services-trusty-mitaka
  inherits: openstack-services
  series: trusty
  overrides:
    openstack-origin: cloud:trusty-mitaka
    source: cloud:trusty-mitaka
  services:
    mongodb:
      branch: https://git.launchpad.net/mongodb-charm
      constraints: mem=1G
    mysql:
      charm: cs:percona-cluster
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
        root-password: ChangeMe123
        sst-password: ChangeMe123
  relations:
    - [ ceilometer, mongodb ]
trusty-mitaka-proposed:
  inherits: trusty-mitaka
  overrides:
    openstack-origin: cloud:trusty-mitaka/proposed
    source: cloud:trusty-mitaka/proposed
trusty-mitaka-staging:
  inherits: trusty-mitaka
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/mitaka-staging
    source: ppa:ubuntu-cloud-archive/mitaka-staging
xenial-mitaka:
  inherits: openstack-services-xenial
  series: xenial
  services:
    mongodb:
      branch: https://git.launchpad.net/mongodb-charm
      constraints: mem=1G
    mysql:
      charm: cs:percona-cluster
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
        root-password: ChangeMe123
        sst-password: ChangeMe123
  relations:
    - [ ceilometer, mongodb ]
xenial-mitaka-proposed:
  inherits: xenial-mitaka
  overrides:
    source: proposed
    openstack-origin: distro-proposed
# ocata
xenial-ocata:
  inherits: openstack-services-xenial-ocata
  series: xenial
  overrides:
    openstack-origin: cloud:xenial-ocata
    source: cloud:xenial-ocata
  services:
    mongodb:
      branch: https://git.launchpad.net/mongodb-charm
      constraints: mem=1G
    mysql:
      charm: cs:percona-cluster
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
        root-password: ChangeMe123
        sst-password: ChangeMe123
  relations:
    - [ ceilometer, mongodb ]
xenial-ocata-proposed:
  inherits: xenial-ocata
  overrides:
    openstack-origin: cloud:xenial-ocata/proposed
    source: cloud:xenial-ocata/proposed
xenial-ocata-staging:
  inherits: xenial-ocata
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/ocata-staging
    source: ppa:ubuntu-cloud-archive/ocata-staging
xenial-ocata-branch:
  inherits: xenial-ocata
  overrides:
    openstack-origin: ppa:openstack-ubuntu-testing/ocata
    source: ppa:openstack-ubuntu-testing/ocata
# pike
xenial-pike:
  inherits: openstack-services-xenial-ocata
  series: xenial
  overrides:
    openstack-origin: cloud:xenial-pike
    source: cloud:xenial-pike
  services:
    mongodb:
      branch: https://git.launchpad.net/mongodb-charm
      constraints: mem=1G
    mysql:
      charm: cs:percona-cluster
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
        root-password: ChangeMe123
        sst-password: ChangeMe123
  relations:
    - [ ceilometer, mongodb ]
xenial-pike-proposed:
  inherits: xenial-pike
  overrides:
    openstack-origin: cloud:xenial-pike/proposed
    source: cloud:xenial-pike/proposed
xenial-pike-staging:
  inherits: xenial-pike
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/pike-staging
    source: ppa:ubuntu-cloud-archive/pike-staging
xenial-pike-branch:
  inherits: xenial-pike
  overrides:
    openstack-origin: ppa:openstack-ubuntu-testing/pike
    source: ppa:openstack-ubuntu-testing/pike
# queens
xenial-queens:
  inherits: openstack-services-queens
  series: xenial
  overrides:
    openstack-origin: cloud:xenial-queens
    source: cloud:xenial-queens
  services:
    mysql:
      charm: cs:percona-cluster
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
        root-password: ChangeMe123
        sst-password: ChangeMe123
xenial-queens-proposed:
  inherits: xenial-queens
  overrides:
    openstack-origin: cloud:xenial-queens/proposed
    source: cloud:xenial-queens/proposed
xenial-queens-staging:
  inherits: xenial-queens
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/queens-staging
    source: ppa:ubuntu-cloud-archive/queens-staging
xenial-queens-branch:
  inherits: xenial-queens
  overrides:
    openstack-origin: ppa:openstack-ubuntu-testing/queens
    source: ppa:openstack-ubuntu-testing/queens
bionic-queens:
  inherits: openstack-services-queens
  series: bionic
  services:
    mysql:
      charm: cs:percona-cluster
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
        root-password: ChangeMe123
        sst-password: ChangeMe123
bionic-queens-proposed:
  inherits: bionic-queens
  overrides:
    source: proposed
    openstack-origin: distro-proposed
bionic-queens-branch:
  inherits: bionic-queens
  overrides:
    openstack-origin: ppa:openstack-ubuntu-testing/queens
    source: ppa:openstack-ubuntu-testing/queens
# rocky
bionic-rocky:
  inherits: openstack-services-rocky
  series: bionic
  overrides:
    openstack-origin: cloud:bionic-rocky
    source: cloud:bionic-rocky
  services:
    mysql:
      charm: cs:percona-cluster
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
        root-password: ChangeMe123
        sst-password: ChangeMe123
bionic-rocky-proposed:
  inherits: bionic-rocky
  overrides:
    openstack-origin: cloud:bionic-rocky/proposed
    source: cloud:bionic-rocky/proposed
bionic-rocky-staging:
  inherits: bionic-rocky
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/rocky-staging
    source: ppa:ubuntu-cloud-archive/rocky-staging
bionic-rocky-branch:
  inherits: bionic-rocky
  overrides:
    openstack-origin: ppa:openstack-ubuntu-testing/rocky
    source: ppa:openstack-ubuntu-testing/rocky
# stein
bionic-stein:
  inherits: openstack-services-rocky
  series: bionic
  overrides:
    openstack-origin: cloud:bionic-stein
    source: cloud:bionic-stein
  services:
    mysql:
      charm: cs:percona-cluster
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
        root-password: ChangeMe123
        sst-password: ChangeMe123
bionic-stein-proposed:
  inherits: bionic-stein
  overrides:
    openstack-origin: cloud:bionic-stein/proposed
    source: cloud:bionic-stein/proposed
bionic-stein-staging:
  inherits: bionic-stein
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/stein-staging
    source: ppa:ubuntu-cloud-archive/stein-staging
bionic-stein-branch:
  inherits: bionic-stein
  overrides:
    openstack-origin: ppa:openstack-ubuntu-testing/stein
    source: ppa:openstack-ubuntu-testing/stein
# train
bionic-train:
  inherits: openstack-services-train
  series: bionic
  overrides:
    openstack-origin: cloud:bionic-train
    source: cloud:bionic-train
  services:
    mysql:
      charm: cs:percona-cluster
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
        root-password: ChangeMe123
        sst-password: ChangeMe123
bionic-train-proposed:
  inherits: bionic-train
  overrides:
    openstack-origin: cloud:bionic-train/proposed
    source: cloud:bionic-train/proposed
bionic-train-staging:
  inherits: bionic-train
  overrides:
    openstack-origin: ppa:ubuntu-cloud-archive/train-staging
    source: ppa:ubuntu-cloud-archive/train-staging
bionic-train-branch:
  inherits: bionic-train
  overrides:
    openstack-origin: ppa:openstack-ubuntu-testing/train
    source: ppa:openstack-ubuntu-testing/train
eoan-train:
  inherits: openstack-services-train
  series: eoan
  services:
    mysql-cluster:
      charm: cs:~openstack-charmers/mysql-innodb-cluster
      constraints: mem=4G
      num_units: 3
    mysql:
      charm: cs:~openstack-charmers/mysql-router
  relations:
    - - mysql-cluster:db-router
      - mysql:db-router
eoan-train-proposed:
  inherits: eoan-train
  overrides:
    source: proposed
    openstack-origin: distro-proposed
eoan-train-branch:
  inherits: eoan-train
  overrides:
    openstack-origin: ppa:openstack-ubuntu-testing/train
    source: ppa:openstack-ubuntu-testing/train
