#!/bin/bash -ex
# An experimental configuration script for configuring a ppc64el OpenStack test cloud.
# Useful in manual deployment testing.

. ./profiles/common

[[ -z "$GATEWAY" ]] && export GATEWAY="10.245.168.1"
[[ -z "$CIDR_EXT" ]] && export CIDR_EXT="10.245.168.0/21"
[[ -z "$FIP_RANGE" ]] && export FIP_RANGE="10.245.175.64:10.245.175.254"
[[ -z "$NAMESERVER" ]] && export NAMESERVER="10.245.168.6"
[[ -z "$CIDR_PRIV" ]] && export CIDR_PRIV="172.16.0.0/22"

export BARE_METAL="True"

# Accept network type as first parameter, assume gre if unspecified
net_type=${1:-"gre"}

# Configure neutron networking on overcloud
source novarc
./bin/neutron-ext-net --network-type flat -g $GATEWAY -c $CIDR_EXT -f $FIP_RANGE ext_net
./bin/neutron-tenant-net --network-type $net_type -t admin -r provider-router -N $NAMESERVER private $CIDR_PRIV

create_tempest_users
create_tempest_flavors
create_default_flavors

# Install monitoring, probing and troubleshooting tools on all units
juju run --all "sudo apt-get install htop atop nload iptraf nmap multitail iperf pastebinit stress sysstat -y"

# Load images into glance
tools/images_arm64.sh

# Set security groups and rules
tools/sec_groups.sh

# Tune for higher-density testing
tools/flavor_shrink.sh
tools/quota_million.sh
