#!/bin/bash

set -ex

# Set cts-stack overrides, if not already set.
[[ -z "$NAMESERVER" ]] && export NAMESERVER="10.230.20.1"
[[ -z "$SWIFT_IP" ]] && export SWIFT_IP="10.245.160.50"

./profiles/default $1 $2 $3 $4 $5
