# vim: set ts=2 et:
# deployer bundle for stable charms
base-services:
  services:
    rabbitmq-server:
      branch: https://github.com/openstack/charm-rabbitmq-server;stable/16.07
      constraints: mem=1G
    ceph:
      branch: https://github.com/openstack/charm-ceph;stable/16.07
      num_units: 3
      constraints: mem=1G
      options:
        monitor-count: 3
        fsid: 6547bd3e-1397-11e2-82e5-53567c8d32dc
        monitor-secret: AQCXrnZQwI7KGBAAiPofmKEXKxu5bUzoYLVkbQ==
        osd-devices: /dev/vdb
        osd-reformat: "yes"
        ephemeral-unmount: /mnt
    keystone:
      branch: https://github.com/openstack/charm-keystone;stable/16.07
      constraints: mem=1G
      options:
        admin-password: openstack
        admin-token: ubuntutesting
    openstack-dashboard:
      branch: https://github.com/openstack/charm-openstack-dashboard;stable/16.07
      constraints: mem=1G
    nova-compute:
      branch: https://github.com/openstack/charm-nova-compute;stable/16.07
      num_units: 3
      constraints: mem=4G
      options:
        enable-live-migration: True
        enable-resize: True
        migration-auth-type: ssh
    nova-cloud-controller:
      branch: https://github.com/openstack/charm-nova-cloud-controller;stable/16.07
      constraints: mem=1G
      options:
        network-manager: Neutron
    neutron-gateway:
      branch: https://github.com/openstack/charm-neutron-gateway;stable/16.07
      constraints: mem=4G
      options:
        instance-mtu: 1300
        bridge-mappings: physnet1:br-ex
    neutron-api:
      branch: https://github.com/openstack/charm-neutron-api;stable/16.07
      constraints: mem=1G
      options:
        neutron-security-groups: True
        flat-network-providers: physnet1
    neutron-openvswitch:
      branch: https://github.com/openstack/charm-neutron-openvswitch;stable/16.07
    cinder:
      branch: https://github.com/openstack/charm-cinder;stable/16.07
      options:
        block-device: "None"
        glance-api-version: 2
      constraints: mem=1G
    glance:
      branch: https://github.com/openstack/charm-glance;stable/16.07
      constraints: mem=1G
    swift-proxy:
      branch: https://github.com/openstack/charm-swift-proxy;stable/16.07
      constraints: mem=1G
      options:
        zone-assignment: manual
        replicas: 3
        swift-hash: fdfef9d4-8b06-11e2-8ac0-531c923c8fae
    swift-storage-z1:
      branch: https://github.com/openstack/charm-swift-storage;stable/16.07
      constraints: mem=1G
      options:
        zone: 1
        block-device: vdb
        overwrite: "true"
    swift-storage-z2:
      branch: https://github.com/openstack/charm-swift-storage;stable/16.07
      constraints: mem=1G
      options:
        zone: 2
        block-device: vdb
        overwrite: "true"
    swift-storage-z3:
      branch: https://github.com/openstack/charm-swift-storage;stable/16.07
      constraints: mem=1G
      options:
        zone: 3
        block-device: vdb
        overwrite: "true"
    ceilometer:
      branch: https://github.com/openstack/charm-ceilometer;stable/16.07
      constraints: mem=1G
    ceilometer-agent:
      branch: https://github.com/openstack/charm-ceilometer-agent;stable/16.07
    heat:
      branch: https://github.com/openstack/charm-heat;stable/16.07
    mongodb:
      branch: https://git.launchpad.net/mongodb-charm
      constraints: mem=1G
  relations:
    - [ keystone, mysql ]
    - [ nova-cloud-controller, mysql ]
    - [ nova-cloud-controller, rabbitmq-server ]
    - [ nova-cloud-controller, glance ]
    - [ nova-cloud-controller, keystone ]
    - [ nova-compute, nova-cloud-controller ]
    - [ nova-compute, mysql ]
    - - nova-compute
      - rabbitmq-server:amqp
    - [ nova-compute, glance ]
    - [ nova-compute, ceph ]
    - [ glance, mysql ]
    - [ glance, keystone ]
    - [ glance, ceph ]
    - [ glance, cinder ]
    - [ glance, rabbitmq-server ]
    - [ cinder, mysql ]
    - [ cinder, rabbitmq-server ]
    - [ cinder, nova-cloud-controller ]
    - [ cinder, keystone ]
    - [ cinder, ceph ]
    - [ neutron-gateway, nova-cloud-controller ]
    - [ openstack-dashboard, keystone ]
    - [ swift-proxy, keystone ]
    - [ swift-proxy, swift-storage-z1 ]
    - [ swift-proxy, swift-storage-z2 ]
    - [ swift-proxy, swift-storage-z3 ]
    - - ceilometer
      - keystone:identity-service
    - [ ceilometer, rabbitmq-server ]
    - [ ceilometer, mongodb ]
    - [ ceilometer-agent, nova-compute ]
    - [ ceilometer-agent, ceilometer ]
    - [ heat, mysql ]
    - [ heat, keystone ]
    - [ heat, rabbitmq-server ]
    - [ "neutron-gateway:amqp", rabbitmq-server ]
    - [ neutron-api, mysql ]
    - [ neutron-api, rabbitmq-server ]
    - [ neutron-api, nova-cloud-controller ]
    - [ neutron-api, neutron-openvswitch ]
    - [ neutron-api, keystone ]
    - [ neutron-api, neutron-gateway ]
    - [ neutron-openvswitch, nova-compute ]
    - [ neutron-openvswitch, rabbitmq-server ]
openstack-services:
  inherits: base-services
  services:
    mysql:
      branch: https://github.com/openstack/charm-percona-cluster;stable/16.07
      constraints: mem=4G
      options:
        dataset-size: 50%
        max-connections: 20000
        root-password: ChangeMe123
        sst-password: ChangeMe123
# liberty
trusty-liberty:
  inherits: openstack-services
  series: trusty
  overrides:
    openstack-origin-git: liberty
    source: cloud:trusty-liberty
trusty-liberty-proposed:
  inherits: trusty-liberty
  overrides:
    source: cloud:trusty-liberty/proposed
# mitaka
trusty-mitaka:
  inherits: openstack-services
  series: trusty
  overrides:
    openstack-origin-git: mitaka
    source: cloud:trusty-mitaka
trusty-mitaka-proposed:
  inherits: trusty-mitaka
  overrides:
    source: cloud:trusty-mitaka/proposed
xenial-mitaka:
  inherits: openstack-services
  series: xenial
  overrides:
    openstack-origin-git: mitaka
xenial-mitaka-proposed:
  inherits: xenial-mitaka
  overrides:
    source: proposed
# newton
xenial-newton:
  inherits: openstack-services
  series: xenial
  overrides:
    openstack-origin-git: newton
    source: cloud:xenial-newton
xenial-newton-proposed:
  inherits: xenial-newton
  overrides:
    source: cloud:xenial-newton/proposed
# master
openstack-master-git:
  inherits: openstack-services
  services:
    keystone:
      options:
        openstack-origin-git: include-file://keystone-master.yaml
    glance:
      options:
        openstack-origin-git: include-file://glance-master.yaml
    cinder:
      options:
        openstack-origin-git: include-file://cinder-master.yaml
    neutron-api:
      options:
        openstack-origin-git: include-file://neutron-master.yaml
    neutron-gateway:
      options:
        openstack-origin-git: include-file://neutron-master.yaml
    neutron-openvswitch:
      options:
        openstack-origin-git: include-file://neutron-master.yaml
    openstack-dashboard:
      options:
        openstack-origin-git: include-file://horizon-master.yaml
    nova-compute:
      options:
        openstack-origin-git: include-file://nova-master.yaml
    nova-cloud-controller:
      options:
        openstack-origin-git: include-file://nova-master.yaml
xenial-master-yaml:
  inherits: openstack-master-git
  series: xenial
  overrides:
    source: cloud:xenial-newton
xenial-master-proposed-yaml:
  inherits: xenial-master-yaml
  overrides:
    source: cloud:xenial-newton/proposed
xenial-master:
  inherits: openstack-services
  series: xenial
  overrides:
    openstack-origin-git: master
    source: cloud:xenial-newton
xenial-master-proposed:
  inherits: xenial-master
  overrides:
    source: cloud:xenial-newton/proposed
